fail_fast: true
repos:
- hooks:
  - exclude: ^.*pb2.py
    id: black
  repo: https://github.com/ambv/black
  rev: stable
- hooks:
  - exclude: ^.*pb2.py
    id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
- hooks:
  - exclude: (^.*(_pb2|_tests)|^.*test.*|^src/db_scripts/.*|^src/apps/processes/.*|^.*/migrations/.*).py$
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.800
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.17.13
